
# SEO settings
title: "Katherine "
title2: "McDonough" # default: ""
description: "Historian"
keywords: "history, academia, mapping, France, European, French"
url: http://kmcdono.com # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-82466685-1
repo: github.kmcdono2.io
disqus_shortname: 
twitter_username: khetiwe24
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : false
  job      : false
  bio      : "I am a historian of France working primarily on the eighteenth century. I write periodically hereÂ about my projects, digital humanities, higher ed, archives, and radio/podcasts."
  thumb    : 
  email    : 
  url      :
  github   : 
  twitter  : 
  facebook : 
  linkedin : 

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@khetiwe24"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog
  - slug : cv
    title: CV  

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
